name: gagavatar-track
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - pytorch3d=0.7.8
  - pip:
      - av==13.0.0
      - face-alignment==1.4.1
      - imageio==2.35.1
      - lmdb==1.5.1
      - lightning==2.4.0
      - matplotlib==3.9.2
      - numba==0.60.0
      - omegaconf==2.3.0
      - onnx==1.16.2
      - onnx2torch==1.5.15
      - opencv-python==4.10.0.84
      - rich==13.8.1
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scipy==1.14.1
      - tqdm==4.66.5
      - torchmetrics==1.4.2
      - transformers==4.45.1
      - yacs==0.1.8
